version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-confeitaria
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: confeit@ri@123T
      MYSQL_DATABASE: confeitaria
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: